package:
  format-version: "1.0.0"
  name: "csp"
  type: "api"
  status: "production"
  required: true
  version: "3.13.1"

  dependencies:
    - name: "dev_packs"
      type: "package"
      version: "3.13.0"
    - name: "harmony-services"
      type: "package"
      version: "1.1.0"
    - name: "CEC_DFP"
      type: "dfp"
      version: "1.5.142"
    - name: "LAN9255_DFP"
      type: "dfp"
      version: "1.3.20"
    - name: "PIC32CM-JH_DFP"
      type: "dfp"
      version: "1.0.88"
    - name: "PIC32CM-LE_DFP"
      type: "dfp"
      version: "1.0.155"
    - name: "PIC32CM-LS_DFP"
      type: "dfp"
      version: "1.0.155"
    - name: "PIC32CM-MC_DFP"
      type: "dfp"
      version: "1.4.67"
    - name: "PIC32CX-BZ_DFP"
      type: "dfp"
      version: "1.0.107"   
    - name: "PIC32CX-SG41_DFP"
      type: "dfp"
      version: "1.0.1"
    - name: "PIC32CX-SG60_DFP"
      type: "dfp"
      version: "1.0.1"
    - name: "PIC32CX-SG61_DFP"
      type: "dfp"
      version: "1.0.1"
    - name: "PIC32MK-GP_DFP"
      type: "dfp"
      version: "1.6.144"
    - name: "PIC32MK-MC_DFP"
      type: "dfp"
      version: "1.10.146"
    - name: "PIC32MM_GPL_DFP"
      type: "dfp"
      version: "1.3.57"
    - name: "PIC32MM_GPM_DFP"
      type: "dfp"
      version: "1.3.50"
    - name: "PIC32MX_DFP"
      type: "dfp"
      version: "1.5.259"
    - name: "PIC32MZ-DA_DFP"
      type: "dfp"
      version: "1.4.118"
    - name: "PIC32MZ-EF_DFP"
      type: "dfp"
      version: "1.3.58"
    - name: "PIC32MZ-W_DFP"
      type: "dfp"
      version: "1.6.217"
    - name: "SAM9X60_DFP"
      type: "dfp"
      version: "1.7.85"
    - name: "SAMA5D2_DFP"
      type: "dfp"
      version: "1.7.91"
    - name: "SAMA7G5_DFP"
      type: "dfp"
      version: "1.0.56" 
    - name: "SAMC20_DFP"
      type: "dfp"
      version: "3.5.93"
    - name: "SAMC21_DFP"
      type: "dfp"
      version: "3.8.119"
    - name: "SAMD09_DFP"
      type: "dfp"
      version: "2.5.147"
    - name: "SAMD10_DFP"
      type: "dfp"
      version: "2.7.81"
    - name: "SAMD11_DFP"
      type: "dfp"
      version: "2.6.76"
    - name: "SAMD20_DFP"
      type: "dfp"
      version: "3.6.112"
    - name: "SAMD21_DFP"
      type: "dfp"
      version: "3.6.144"
    - name: "SAMD51_DFP"
      type: "dfp"
      version: "3.6.120"
    - name: "SAMDA1_DFP"
      type: "dfp"
      version: "2.7.82"
    - name: "SAME51_DFP"
      type: "dfp"
      version: "3.6.130"
    - name: "SAME53_DFP"
      type: "dfp"
      version: "3.6.115"
    - name: "SAME54_DFP"
      type: "dfp"
      version: "3.7.122"
    - name: "SAME70_DFP"
      type: "dfp"
      version: "4.9.129"
    - name: "SAMG_DFP"
      type: "dfp"
      version: "3.7.83"
    - name: "SAMHA0_DFP"
      type: "dfp"
      version: "2.2.63"
    - name: "SAMHA1_DFP"
      type: "dfp"
      version: "2.4.81"
    - name: "SAML10_DFP"
      type: "dfp"
      version: "3.9.116"
    - name: "SAML11_DFP"
      type: "dfp"
      version: "4.4.149"
    - name: "SAML21_DFP"
      type: "dfp"
      version: "3.6.105"
    - name: "SAML22_DFP"
      type: "dfp"
      version: "3.7.83"
    - name: "SAMR21_DFP"
      type: "dfp"
      version: "2.0.42"
    - name: "SAMR30_DFP"
      type: "dfp"
      version: "2.0.40"
    - name: "SAMR34_DFP"
      type: "dfp"
      version: "2.1.60"
    - name: "SAMR35_DFP"
      type: "dfp"
      version: "2.1.63"
    - name: "SAMRH71_DFP"
      type: "dfp"
      version: "2.5.142"
    - name: "SAMRH707_DFP"
      type: "dfp"
      version: "1.1.43"
    - name: "SAMS70_DFP"
      type: "dfp"
      version: "4.9.103"
    - name: "SAMV70_DFP"
      type: "dfp"
      version: "4.9.100"
    - name: "SAMV71_DFP"
      type: "dfp"
      version: "4.9.117"
    - name: "WLR089_DFP"
      type: "dfp"
      version: "1.0.18"
