package:
  format-version: "1.0.0"
  name: "csp"
  type: "api"
  status: "production"
  required: true
  version: "3.13.0"

  dependencies:
    - name: "dev_packs"
      type: "package"
      version: "3.10.0"
    - name: "harmony-services"
      type: "package"
      version: "1.1.0"
    - name: "CEC_DFP"
      type: "dfp"
      version: "1.5.142"
    - name: "LAN9255_DFP"
      type: "dfp"
      version: "1.2.12"
    - name: "PIC32CM-JH_DFP"
      type: "dfp"
      version: "1.0.80"
    - name: "PIC32CM-LE_DFP"
      type: "dfp"
      version: "1.0.153"
    - name: "PIC32CM-LS_DFP"
      type: "dfp"
      version: "1.0.153"
    - name: "PIC32CM-MC_DFP"
      type: "dfp"
      version: "1.3.58"
    - name: "PIC32CX-BZ_DFP"
      type: "dfp"
      version: "1.0.80"
    - name: "PIC32CX-SG41_DFP"
      type: "dfp"
      version: "1.0.1"
    - name: "PIC32CX-SG60_DFP"
      type: "dfp"
      version: "1.0.1"
    - name: "PIC32CX-SG61_DFP"
      type: "dfp"
      version: "1.0.1"
    - name: "PIC32MK-GP_DFP"
      type: "dfp"
      version: "1.6.144"
    - name: "PIC32MK-MC_DFP"
      type: "dfp"
      version: "1.9.143"
    - name: "PIC32MM_GPL_DFP"
      type: "dfp"
      version: "1.3.57"
    - name: "PIC32MM_GPM_DFP"
      type: "dfp"
      version: "1.3.50"
    - name: "PIC32MX_DFP"
      type: "dfp"
      version: "1.5.259"
    - name: "PIC32MZ-DA_DFP"
      type: "dfp"
      version: "1.4.118"
    - name: "PIC32MZ-EF_DFP"
      type: "dfp"
      version: "1.3.58"
    - name: "PIC32MZ-W_DFP"
      type: "dfp"
      version: "1.5.203"
    - name: "SAM9X60_DFP"
      type: "dfp"
      version: "1.6.61"
    - name: "SAMA5D2_DFP"
      type: "dfp"
      version: "1.6.69"
    - name: "SAMC20_DFP"
      type: "dfp"
      version: "3.4.76"
    - name: "SAMC21_DFP"
      type: "dfp"
      version: "3.5.95"
    - name: "SAMD09_DFP"
      type: "dfp"
      version: "2.4.129"
    - name: "SAMD10_DFP"
      type: "dfp"
      version: "2.5.64"
    - name: "SAMD11_DFP"
      type: "dfp"
      version: "2.4.56"
    - name: "SAMD20_DFP"
      type: "dfp"
      version: "3.4.68"
    - name: "SAMD21_DFP"
      type: "dfp"
      version: "3.4.116"
    - name: "SAMD51_DFP"
      type: "dfp"
      version: "3.5.95"
    - name: "SAMDA1_DFP"
      type: "dfp"
      version: "2.5.68"
    - name: "SAME51_DFP"
      type: "dfp"
      version: "3.5.104"
    - name: "SAME53_DFP"
      type: "dfp"
      version: "3.5.87"
    - name: "SAME54_DFP"
      type: "dfp"
      version: "3.6.95"
    - name: "SAME70_DFP"
      type: "dfp"
      version: "4.6.98"
    - name: "SAMG_DFP"
      type: "dfp"
      version: "3.5.65"
    - name: "SAMHA0_DFP"
      type: "dfp"
      version: "2.1.52"
    - name: "SAMHA1_DFP"
      type: "dfp"
      version: "2.2.68"
    - name: "SAML10_DFP"
      type: "dfp"
      version: "3.8.105"
    - name: "SAML11_DFP"
      type: "dfp"
      version: "4.3.139"
    - name: "SAML21_DFP"
      type: "dfp"
      version: "3.5.87"
    - name: "SAML22_DFP"
      type: "dfp"
      version: "3.5.68"
    - name: "SAMR21_DFP"
      type: "dfp"
      version: "2.0.42"
    - name: "SAMR30_DFP"
      type: "dfp"
      version: "2.0.40"
    - name: "SAMR34_DFP"
      type: "dfp"
      version: "2.1.60"
    - name: "SAMR35_DFP"
      type: "dfp"
      version: "2.1.62"
    - name: "SAMRH707_DFP"
      type: "dfp"
      version: "1.0.28"
    - name: "SAMRH71_DFP"
      type: "dfp"
      version: "2.3.124"
    - name: "SAMS70_DFP"
      type: "dfp"
      version: "4.6.82"
    - name: "SAMV70_DFP"
      type: "dfp"
      version: "4.5.75"
    - name: "SAMV71_DFP"
      type: "dfp"
      version: "4.6.90"
    - name: "WLR089_DFP"
      type: "dfp"
      version: "1.0.17"
